import type { Metadata } from 'next';
import { Inter as FontSans } from 'next/font/google';
import './globals.css';
import { cn } from '@/lib/utils';
import { Providers } from './providers';
import { TailwindIndicator } from '@/components/utils/TailwindIndicator';
import { NextTopLoader } from '@/components/utils/NextTopLoader';

const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' className='h-full' suppressHydrationWarning>
      <body className={cn('h-full bg-background font-sans antialiased', fontSans.variable)}>
        <Providers>
          <NextTopLoader delay={100} showSpinner={false} color='hsl(var(--primary))' />
          {children}
          <TailwindIndicator />
        </Providers>
      </body>
    </html>
  );
}
